apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace  annotations:
  argocd.argoproj.io/hook: Sync
  argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
  argocd.argoproj.io/sync-wave: "1"
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: db-migration   
    spec:
      containers: 
        - name: migration
          image: snehalpawar2945/easyshop-migration:4
          imagePullPolicy: Always
          env:
            - name: MONGODB_URI
              value: "mongodb://mongodb-svc:27017/easyshop"
      
      restartPolicy: OnFailure
