apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: easyshop-ns
spec:
  serviceName: mongodb-svc
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
        name: mongodb
        namespace: easyshop-ns
        labels:
          app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:7.0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
          readinessProbe:
            exec:
              command:
                - mongosh
                - --quiet
                - --eval
                - db.adminCommand('ping').ok
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 12
            successThreshold: 1

          livenessProbe:
            exec:
              command:
                - mongosh
                - --quiet
                - --eval
                - db.adminCommand('ping').ok
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc
